DROP table  IF EXISTS REVISERS;
create table REVISERS
(
    ID            BIGINT AUTO_INCREMENT,
    SURNAME VARCHAR(36) NOT NULL,
    NAME       VARCHAR(36) NOT NULL,
    AGE      VARCHAR(36) NOT NULL,
    ENTRY_DATE  DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)

);

DROP table  IF EXISTS TEACHERS;
CREATE TABLE TEACHERS
(
    ID            BIGINT AUTO_INCREMENT,
    SURNAME VARCHAR(36) NOT NULL,
    NAME       VARCHAR(36) NOT NULL,
    AGE      INT NOT NULL,
    ENTRY_DATE   DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

DROP table  IF EXISTS STUDENTS;
CREATE TABLE STUDENTS
(
    ID            BIGINT AUTO_INCREMENT,
    SURNAME VARCHAR(36) NOT NULL,
    NAME       VARCHAR(36) NOT NULL,
    AGE      INT NOT NULL,
    GROUP_ID   BIGINT  NULL,
    ENTRY_DATE   DATETIME  NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (GROUP_ID) REFERENCES STUDENT_GROUPS(ID)
);



CREATE TABLE STUDENT_GROUPS
( 
    ID            BIGINT AUTO_INCREMENT,
    GROUP_NAME VARCHAR(1000) NOT NULL, 
    TEACHER_ID BIGINT  NOT NULL,
    REVISER_ID BIGINT  NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (TEACHER_ID) REFERENCES TEACHERS(ID),
    FOREIGN KEY (REVISER_ID) REFERENCES REVISERS(ID) 
);

